<?php

namespace Baby\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function getVotesCountGroupedByVote() {
        $qb = $this->createQueryBuilder('v');
        $qb->select('count(v.id) as num, v.vote');
        $qb->addGroupBy('v.vote');

        return $qb->getQuery()->getResult();
    }

}
